# Generated by Django 4.2.7 on 2023-12-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_adress_appoinment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specilisation',
            new_name='specialization',
        ),
    ]
